version: "3.8"

services:
  app:
    container_name: cassia-frontend-qa
    image: cassia-frontend-qa
    network_mode: "host"
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 8003:8003
