version: "3.8"

services:
  app:
    container_name: cassia-frontend-qa
    image: cassia-frontend-qa
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 8003:8003
    networks:
      - front_qa_network
networks:
  front_network:
    driver: host
    external: true
    name: front_qa_network